language: cpp

sudo: false

compiler:
  - gcc-4.8

#addon:
#  apt:
#   sources:
#    - ubuntu-toolchain-r-test
#   packages:
#    - g++-4.8

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script:
  - make
